# Generated by Django 3.2.5 on 2021-07-14 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covid_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idc', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idp', models.IntegerField(max_length=4)),
                ('startD', models.DateTimeField()),
                ('endD', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.AddField(
            model_name='county',
            name='patient_count',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='covid_map.patient'),
        ),
    ]
