# Generated by Django 3.2.5 on 2021-07-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_map', '0002_auto_20210714_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='patient_count',
            field=models.IntegerField(max_length=10),
        ),
    ]
